CREATE DATABASE [PasswordManager]
GO

USE [PasswordManager]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](max) NULL,
	[Password] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
	[RegisterDate] [datetime] NULL,
	[ModifyDate] [datetime] NULL,
 CONSTRAINT [PK_TBL_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [PasswordManager]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_CATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[CategoryName] [nvarchar](max) NULL,
 CONSTRAINT [PK_TBL_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_CATEGORY]  WITH CHECK ADD  CONSTRAINT [FK_TBL_CATEGORY_TBL_USER] FOREIGN KEY([UserID])
REFERENCES [dbo].[TBL_USER] ([ID])
GO

ALTER TABLE [dbo].[TBL_CATEGORY] CHECK CONSTRAINT [FK_TBL_CATEGORY_TBL_USER]
GO

USE [PasswordManager]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_PASSWORD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[PasswordName] [nvarchar](max) NULL,
	[Username] [nvarchar](max) NULL,
	[Password] [nvarchar](max) NULL,
	[URL] [nvarchar](max) NULL,
	[CategoryID] [int] NOT NULL,
 CONSTRAINT [PK_TBL_PASSWORD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_PASSWORD]  WITH CHECK ADD  CONSTRAINT [FK_TBL_PASSWORD_TBL_CATEGORY] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[TBL_CATEGORY] ([ID])
GO

ALTER TABLE [dbo].[TBL_PASSWORD] CHECK CONSTRAINT [FK_TBL_PASSWORD_TBL_CATEGORY]
GO

ALTER TABLE [dbo].[TBL_PASSWORD]  WITH CHECK ADD  CONSTRAINT [FK_TBL_PASSWORD_TBL_USER] FOREIGN KEY([UserID])
REFERENCES [dbo].[TBL_USER] ([ID])
GO

ALTER TABLE [dbo].[TBL_PASSWORD] CHECK CONSTRAINT [FK_TBL_PASSWORD_TBL_USER]
GO
